In [9]:
# Import TensorFlow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.10.0


# 🛠 00. TensorFlow Fundamentals Exercises
- Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
- Find the shape, rank and size of the tensors you created in 1.
- Create two tensors containing random values between 0 and 1 with shape [5, 300].
- Multiply the two tensors you created in 3 using matrix multiplication.
- Multiply the two tensors you created in 3 using dot product.
- Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
- Find the min and max values of the tensor you created in 6 along the first axis.
- Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
- Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
- One-hot encode the tensor you created in 9.

In [3]:
scalar = tf.constant(8)
vector = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[4,5,6]])
tensor = tf.constant([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [5]:
scalar.shape, scalar.ndim, tf.size(scalar), tf.rank(scalar)

(TensorShape([]),
 0,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [6]:
vector.shape, vector.ndim, tf.size(vector), tf.rank(vector)

(TensorShape([3]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [7]:
matrix.shape, matrix.ndim, tf.size(matrix), tf.rank(matrix)

(TensorShape([2, 3]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [8]:
tensor.shape, tensor.ndim, tf.size(tensor), tf.rank(tensor)

(TensorShape([2, 2, 3]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [12]:
tf.random.set_seed(42)
tensor1 = tf.random.uniform(shape=(5,300))
tensor2 = tf.random.uniform(shape=(5,300))

tensor1, tensor1.shape, tensor2, tensor2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

In [15]:
dotpro = tensor1@tf.transpose(tensor2)
dotpro, dotpro.shape

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.333435, 73.40498 , 77.15962 , 73.98368 , 80.90054 ],
        [75.14635 , 68.80437 , 74.24302 , 71.841835, 75.602066],
        [79.7594  , 75.64456 , 77.797585, 74.74873 , 80.559845],
        [75.08526 , 69.06406 , 74.30776 , 72.27615 , 76.05668 ],
        [85.0569  , 74.266266, 78.00686 , 74.88679 , 83.13417 ]],
       dtype=float32)>,
 TensorShape([5, 5]))

In [16]:
random_values = tf.random.uniform(shape = [224, 224 , 3 ], minval = 0 , maxval = 1 )
random_values, random_values.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.7413678 , 0.62854624, 0.01738465],
         [0.3431449 , 0.51063764, 0.3777541 ],
         [0.07321596, 0.02137029, 0.2871771 ],
         ...,
         [0.98953485, 0.45382905, 0.2006687 ],
         [0.6295223 , 0.4937899 , 0.01816809],
         [0.95386636, 0.11542463, 0.85691285]],
 
        [[0.78435016, 0.7826872 , 0.87936425],
         [0.24906898, 0.3207239 , 0.10955775],
         [0.543224  , 0.7151396 , 0.40334642],
         ...,
         [0.2445668 , 0.01746976, 0.9036933 ],
         [0.02975535, 0.592268  , 0.9877522 ],
         [0.36701274, 0.33112562, 0.5638567 ]],
 
        [[0.15829337, 0.7288823 , 0.3366307 ],
         [0.70792687, 0.16910625, 0.9429966 ],
         [0.10120225, 0.5919596 , 0.8687303 ],
         ...,
         [0.28134012, 0.10011208, 0.37038183],
         [0.77874243, 0.05421627, 0.4664607 ],
         [0.2549187 , 0.7968637 , 0.83405185]],
 
        ...,
 
        [[0.32922816, 0.06343532

In [18]:
tf.reduce_min(random_values), tf.reduce_max(random_values)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999918>)

In [19]:
newtensor = tf.random.uniform(shape = [1,224,224,3])
tf.squeeze(newtensor), tf.squeeze(newtensor).shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
         [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
         [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
         ...,
         [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
         [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
         [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],
 
        [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
         [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
         [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
         ...,
         [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
         [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
         [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],
 
        [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
         [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
         [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
         ...,
         [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],


In [20]:
infex = tf.constant([1,2,3,4,5,6,7,8,9,10])
tf.argmax(infex)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [21]:
tf.one_hot(infex, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>